### ISSUE TITLE
IGDM Pro Licence

### ISSUE THREAD

**Issue by nikitasingh124** [igdmapps/igdm-pro-release#69]
How to purchase license key .

where is the payment link am not able find.

kind send me payment link so that purchase license key

**Comment by ifedapoolarewaju** [comment]
Hi, the payment link was temporarily disabled because the IGdm Pro app was broken and needed some fixes. We didn't want to have people pay for a broken app.

A completely new version has now been released with the payment link now re-enabled.

Please visit https://pro.igdm.me/ to download the latest version
