### ISSUE TITLE
the bulk messnger

### ISSUE THREAD

**Issue by tobisamaa** [igdmapps/igdm-pro-release#75]
hi iloved the profuct -
the bulk messnenger has somthing that slowing it down its very slow  but if i reclick on pause and resume each 7 sexonds it shoots them like a machine maybe you can do witht htat info somthing to fix that issue

**Comment by ifedapoolarewaju** [comment]
Hi @tobisamaa the delay in the bulk messages is intentional. Otherwise, you risk getting your account blocked by Instagram if you send so much messages too rapidly.

Please see this note from one of our articles.

<img width="780" alt="image" src="https://github.com/igdmapps/igdm-pro-release/assets/8383781/613b6f35-3e02-49bd-a38e-1795345b5c11">
